name: Workflow To Deploy To Testing Server (EC2)

run-name: ${{github.actor}} initiated the workflow - Deploy To Testing

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out
        uses: actions/checkout@v4

      - name: Setting Up Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: Testing Node Installation
        run:  |
          node --version

      - name: Install dependencies
        run:  |
          cd React_App
          npm install

      - name: Building Project
        run: |
          cd React_App
          npm run build-react

      - name: Testing The Project
        run: |
          cd React_App
          npm run test-react

      - name: Notify on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          subject: Github Action Sucess
          to: ashhar.shah786@gmail.com
          from: ashhar.shah786@gmail.com
          body: Workflow of ${{github.repository}} completed successfully!
          html_body: file://README.html