name: Workflow To Deploy To Testing Server (EC2)

run-name: ${{github.actor}} initiated the workflow - Deploy To Testing

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out
        uses: actions/checkout@v4

      - name: Setting Up Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: Testing Node Installation
        run:  |
          node --version

      - name: Install dependencies
        run:  |
          cd React_App
          npm install

      - name: Building Project
        run: |
          cd React_App
          npm run build-react

      - name: Testing The Project
        run: |
          cd React_App
          npm run test-react