# name of the workflow
name: Workflow To Deploy To Testing Server (EC2)

# run name for the workflow
run-name: ${{github.actor}} initiated the workflow - Deploy To Testing

# when to trigger the workflow
on:
  push:
    branches:
      - master

# what to do once the workflow is triggered
jobs:
  deploy:
    # enviroment for the runners
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out
        uses: actions/checkout@v4
        
        # setting up NodeJS on the runner
      - name: Setting Up Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: Testing Node Installation
        run:  |
          node --version
      
      # installing any dependencies
      - name: Install dependencies
        run:  |
          cd React_App
          npm install

      # building the project (checking for build errors)
      - name: Building Project
        run: |
          cd React_App
          npm run build-react

      # running unit tests on the application
      - name: Testing The Project
        run: |
          cd React_App
          npm run test-react

      # notifying the QA and the Developer on workflow sucess.
      - name: Notify on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          subject: Github Action Sucess
          to: ashhar.shah786@gmail.com
          from: ashhar.shah786@gmail.com
          body: Workflow of ${{github.repository}} completed successfully!

      # Deploy All Changes To The Testing Server
      - name: Deploy To Changes To Testing Server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ~/
          remote_host: 54.210.17.12
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_KEY }}

      # Restart the service and display the new application
      - name: Restarting Our Application
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 54.210.17.12
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo systemctl restart nginx.service
            cd React_App
            npm install
            node index.js &